"""
FastAPI Backend for StudyMate
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import os
from datetime import datetime
from typing import Optional
import uuid

app = FastAPI(
    title="StudyMate API",
    description="AI Teaching Agent using Questioning Method",
    version="1.0.0"
)

# Enable CORS (for Streamlit to connect)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory storage (will add agent integration later)
sessions = {}

# Request/Response Models
class SessionCreate(BaseModel):
    github_url: str
    student_name: Optional[str] = "Student"
    knowledge_level: Optional[str] = "intermediate"

class ChatMessage(BaseModel):
    session_id: str
    message: str

class SessionResponse(BaseModel):
    session_id: str
    greeting: str
    repo_analyzed: bool

class ChatResponse(BaseModel):
    response: str
    session_id: str


# Root endpoint
@app.get("/")
async def root():
    return {
        "status": "healthy",
        "service": "StudyMate API",
        "version": "1.0.0"
    }


# Health check
@app.get("/health")
async def health():
    return {
        "status": "healthy",
        "active_sessions": len(sessions),
        "openai_key_configured": bool(os.getenv("OPENAI_API_KEY")),
        "timestamp": datetime.now().isoformat()
    }


# Create session endpoint
@app.post("/session/create", response_model=SessionResponse)
async def create_session(session_data: SessionCreate):
    """
    Creates a new learning session.
    For now, just returns a mock response.
    We'll add repo cloning + agent initialization later.
    """
    # Generate session ID
    session_id = str(uuid.uuid4())
    
    # Store session info
    sessions[session_id] = {
        "id": session_id,
        "github_url": session_data.github_url,
        "student_name": session_data.student_name,
        "knowledge_level": session_data.knowledge_level,
        "created_at": datetime.now().isoformat(),
        "messages": []
    }
    
    # Mock greeting (will be generated by agent later)
    greeting = f"""Hello {session_data.student_name}! 👋

I'm StudyMate, your AI learning companion. I'll help you understand the repository you shared through guided discovery.

Before we dive in, tell me: **What interests you most about this project?**"""
    
    # Store greeting
    sessions[session_id]["messages"].append({
        "role": "assistant",
        "content": greeting,
        "timestamp": datetime.now().isoformat()
    })
    
    return SessionResponse(
        session_id=session_id,
        greeting=greeting,
        repo_analyzed=True  # Mock for now
    )


# Chat endpoint
@app.post("/chat", response_model=ChatResponse)
async def chat(chat_msg: ChatMessage):
    """
    Handles student messages.
    For now, returns echo response.
    We'll add agent integration later.
    """
    # Validate session
    if chat_msg.session_id not in sessions:
        raise HTTPException(status_code=404, detail="Session not found")
    
    session = sessions[chat_msg.session_id]
    
    # Store student message
    session["messages"].append({
        "role": "user",
        "content": chat_msg.message,
        "timestamp": datetime.now().isoformat()
    })
    
    # Mock response (will be generated by agent later)
    response = f"I received your message: '{chat_msg.message}'. (Agent integration coming next!)"
    
    # Store response
    session["messages"].append({
        "role": "assistant",
        "content": response,
        "timestamp": datetime.now().isoformat()
    })
    
    return ChatResponse(
        response=response,
        session_id=chat_msg.session_id
    )


# Get session history
@app.get("/session/{session_id}/history")
async def get_history(session_id: str):
    """Returns conversation history for a session."""
    if session_id not in sessions:
        raise HTTPException(status_code=404, detail="Session not found")
    
    return {
        "session_id": session_id,
        "messages": sessions[session_id]["messages"]
    }


# Main entry point
if __name__ == "__main__":
    import uvicorn
    
    print("🚀 Starting StudyMate API...")
    print("📚 Endpoints available:")
    print("   GET  /              - Root")
    print("   GET  /health        - Health check")
    print("   POST /session/create - Create session")
    print("   POST /chat          - Chat with agent")
    print("   GET  /session/{id}/history - Get history")
    print()
    
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )
